export const ActionTypes = {
    LOGIN : "LOGIN",
    REGISTER : "REGISTER",
    SETMOVIELIST : "SETMOVIELIST",
    ADDMOVIELIST : "ADDMOVIELIST",
    EDITMOVIELIST : "EDITMOVIELIST",
    DELETEMOVIELIST : "DELETEMOVIELIST",
    SETGENRELIST : "SETGENRELIST",
    ADDGENRELIST : "ADDGENRELIST",
    SNACKBAR_SHOW: "SNACKBAR_SHOW",
    GETSINGLEDATA: "GETSINGLEDATA",
    SEARCHDATA: "SEARCHDATA"
}